version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 33782:1972
      - 33783:52773
      - 33784:53773
      - 8888:8888
    volumes:
      - ./:/irisdev/app